---
name: Release AtlasCLI
on:
  push:
    tags: ['*']
      # - atlascli_*
  pull_request:
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install goreleaser
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install goreleaser-pro
      - run: |
          ./build/package/generate-notices.sh
          export VERSION_GIT="$(git tag --list "atlascli_v*" --sort=taggerdate | tail -1 | cut -d "v" -f 2)"
          goreleaser --config "build/package/.atlascli.goreleaser.yml" --rm-dist --release-notes "CHANGELOG_ATLASCLI.md" -p 1 --debug
