---
name: Sync Fork
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  sync-fork:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: go install github.com/golang/mock/mockgen@latest
      - run: |
          find . -type f | grep -v .git | xargs sed -i'' 's|github.com/mongodb/mongodb-atlas-cli|github.com/fmenezes/mongodb-atlas-cli|'
          find . -type f -name '*.go' -exec goimports -w {} +;
          make gen-mocks
      - uses: peter-evans/create-pull-request@v6
        with:
          title: Sync fork
          commit-message: Sync fork
          delete-branch: true
          base: master
          branch: sync-fork
          body: |
            Sync fork
